/* This file was automatically generated by CasADi 3.7.1.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

int ceq2_func(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int ceq2_func_alloc_mem(void);
int ceq2_func_init_mem(int mem);
void ceq2_func_free_mem(int mem);
int ceq2_func_checkout(void);
void ceq2_func_release(int mem);
void ceq2_func_incref(void);
void ceq2_func_decref(void);
casadi_int ceq2_func_n_in(void);
casadi_int ceq2_func_n_out(void);
casadi_real ceq2_func_default_in(casadi_int i);
const char* ceq2_func_name_in(casadi_int i);
const char* ceq2_func_name_out(casadi_int i);
const casadi_int* ceq2_func_sparsity_in(casadi_int i);
const casadi_int* ceq2_func_sparsity_out(casadi_int i);
int ceq2_func_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int ceq2_func_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define ceq2_func_SZ_ARG 5
#define ceq2_func_SZ_RES 1
#define ceq2_func_SZ_IW 0
#define ceq2_func_SZ_W 0
#ifdef __cplusplus
} /* extern "C" */
#endif
